---
title: "binary"
author: "STEPHEN ODHIAMBO OGAJA"
date: '2022-08-04'
output: pdf_document
---

```{r}
library(mlbench)
library(MASS)
library(pROC)
data(PimaIndiansDiabetes2)
head(PimaIndiansDiabetes2)
```
```{r}
# descriptive stats 
summary(PimaIndiansDiabetes2)

```

```{R}
# removing the missing values
newdata <- na.omit(PimaIndiansDiabetes2)
summary(newdata)
```

```{R}
# visualization
par(mfrow = c(4,2))
for( i in 1:8){
  hist(newdata[,i], main = colnames(newdata)[i],xlab =     colnames(newdata)[i], col = 'yellow')
}
```

```{R}
newdata$age_bucket <- as.factor(ifelse(newdata$age<=30,"20-30",ifelse(newdata$age<=40,"31-40",ifelse(newdata$age<=50,"41-50","50+"))))

newdata$preg_bucket <- as.factor(ifelse(newdata$pregnant<=5,"0–5",ifelse(newdata$pregnant<=10,"6–10","10+")))

```

```{R}
par(mfrow = c(3,2))
boxplot(glucose~diabetes, ylab="Glucose", xlab= "Diabetes", col="light blue",data = newdata)
boxplot(pressure~diabetes, ylab="Pressure", xlab= "Diabetes", col="light blue",data = newdata)
boxplot(triceps~diabetes, ylab="triceps", xlab= "Diabetes", col="light blue",data = newdata)
boxplot(insulin~diabetes, ylab="Insulin", xlab= "Diabetes", col="light blue",data = newdata)
boxplot(mass~diabetes, ylab="Mass", xlab= "Diabetes", col="light blue",data = newdata)
boxplot(pedigree~diabetes, ylab="Pedigree", xlab= "Diabetes", col="light blue",data = newdata)
```

```{R}
xtabs(~diabetes + age_bucket, data = newdata)
xtabs(~diabetes + preg_bucket, data = newdata)
```
```{R}
# creating a dataframe with relevant columns for modelling
newdata2 <- newdata[,c("diabetes","glucose","pressure","triceps","insulin","mass","pedigree","age_bucket","preg_bucket")]
```


```{R}
# passing in the glm model on the data
logit_1 <- glm(diabetes~., family = binomial,data = newdata2)
```

```{R}
summary(logit_1)
```

```{R}
# variable selection
logit_2 <- stepAIC(logit_1)
```


```{R}
# new model summary
summary(logit_2)
```

```{R}
# summary
summary(logit_2$fitted.values)

# visualization
hist(logit_2$fitted.values,main = " Histogram ",xlab = "Probability of 'pos' diabetes", col = 'light green')

```
```{R}
roc(diabetes~logit_2$fitted.values, data = newdata2, plot = TRUE, main = "ROC CURVE", col= "blue")
```

```{R}
input <- warpbreaks
print(head(input))
```

```{R}
output <-glm(formula = breaks ~ wool+tension, data = warpbreaks,
   family = poisson)
print(summary(output))
```










