---
title: "MESA8668 - Matrix Operations"
author: "Steve"
output:
  pdf_document:
fontsize: 12pt
geometry: margin = 0.8in
header-includes:
- \setlength\parindent{24pt}
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{array}
- \usepackage{graphicx}
- \usepackage{caption}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE, message=FALSE, warning=FALSE, comment=NA, 
  fig.height=8, fig.width=8,
  tidy.opts=list(width.cutoff=60), tidy=TRUE
)
options(max.print = 2000, tibble.print_max = 100)
```


```{r results='hide'}
#empty environment.
rm(list = ls())
```




# **1. Vectors** #
```{r}
a <- as.matrix(c(1,0,0))
print(a)

b <- as.matrix(c(1,-1,1,-1))
print(b)

y <- as.matrix(c(1,2,-2))
print(y)


# There is also a way to easily create matrices.
# Create a 3x4 matrix with elements ranging from 1 to 12.
a <- matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE)
a
```

\newpage

# **2. Scalar multiplication** #
```{r}
c <- 5
c.y <- c * y
print(c.y)
```



# **3. Vector addition** #
```{r}
x <- as.matrix(c(3,-1,4))
z <- x + y
print(z)
```




# **4. Dimensions of a vector/matrix** #
```{r}
dim(y)
```



# **5. Matrix addition** #
```{r}
A <- as.matrix(rbind(c(3,2,3), c(4,1,1)))
print(A)
```

\newpage

```{r}
B <- as.matrix(rbind(c(3,6,7), c(2,-1,0)))
print(B)

C <- A + B
print(C)
```



# **6. Scalar multiplication** #
```{r}
c <- 2
A <- as.matrix(cbind(c(3,2,0), c(-4,6,5)))

B1 <- c * A
B2 <- A * c

print(B1)
print(B2)
```



# **7. Transpose of a matrix** #
```{r}
A <- as.matrix(rbind(c(2,1,3), c(7,-4,6)))
print(A)

t(A) # transpose of A.

dim(A) # dimensions of A.
dim(t(A)) # dimensions of transposed A.

B <- as.matrix(rbind(c(2,-3), c(4,1)))
print(B)

t(B) # transpose of B.

dim(B) # dimensions of B.
dim(t(B)) # dimensions of transposed B.

a <- as.matrix(c(2,-3,1))
print(a)

t(a) # transpose of a.
```

\newpage

```{r}
dim(a) # dimensions of a.
dim(t(a)) # dimensions of transposed a.


# tranpose of a trasposed matrix.
A <- as.matrix(rbind(c(2,1,3), c(7,-4,6)))
print(A)
t(t(A))
```



# **8. A symmetric matrix** #
```{r}
A <- as.matrix(rbind(c(3,-2,4), c(-2,10,-7), c(4,-7,9)))
print(A)
t(A)

```


\newpage

# **9. Special matrices** #
```{r}
# Diagonal matrix.
diag(c(10,-3,9,7), 4, 4)

# Identity matrix.
diag(1, 3, 3)

# Upper triangular matrix.
A <- as.matrix(rbind(c(3,-2,4), c(-2,10,-7), c(4,-7,9)))
upper.tri(A) # a matrix of logicals.
A[lower.tri(A)] <- 0
print(A)

A[lower.tri(A, diag = TRUE)] <- 0 # also, remove the diagonal.
print(A)
```

\newpage

```{r}
# Lower triangular matrix.
A <- as.matrix(rbind(c(3,-2,4), c(-2,10,-7), c(4,-7,9)))
lower.tri(A) # a matrix of logicals.
A[upper.tri(A)] <- 0
print(A)

A[upper.tri(A, diag = TRUE)] <- 0 # also, remove the diagonal.
print(A)
```



# **10. Multiplication of matrices and vectors** #
```{r}
A <- as.matrix(cbind(c(2,4,7,1), c(1,6,2,3), c(3,5,3,2)))
B <- as.matrix(cbind(c(1,2,3), c(4,6,8)))

C <- A %*% B
C

A <- matrix(1:4, nrow = 2)
B <- as.matrix(cbind(c(1,3), c(-2,5)))
```

\newpage

```{r}
AB <- A %*% B
AB

BA <- B %*% A
BA
```



# **11. a'a and aa'** #
```{r}
a <- as.matrix(c(1,5,3,10))
a

a.a <- t(a) %*% a
a.a

aa. <- a %*% t(a)
aa.
```

\newpage

# **12. Rank of a matrix** #
```{r}
# Matrix package needed for the "rankMatrix" function.
A <- as.matrix(cbind(c(1,2), c(1,5)))
Matrix::rankMatrix(A) 

A <- as.matrix(cbind(c(1,2,0), c(1,5,1), c(1,-1,-1)))
Matrix::rankMatrix(A) 
```



# **13. Determinant of a matrix** #
```{r}
A <- as.matrix(cbind(c(1,6), c(3,4)))
det(A)

B <- as.matrix(cbind(c(3,7,2), c(1,4,-7), c(6,5,1)))
det(B)
```

\newpage

# **14. Inverse of a matrix** #
```{r}
A <- as.matrix(cbind(c(3,2), c(4,6)))
A_inv <- solve(A)
A_inv

A %*% A_inv
```




